// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Offer struct {
	ID                      uuid.UUID
	CreatedAt               time.Time
	UpdatedAt               time.Time
	Title                   string
	Organization            string
	OrganizationDescription sql.NullString
	Missions                []string
	Stack                   []string
	ExpectedProfile         []string
	Miscellaneous           []string
	UserID                  uuid.UUID
}

type RawEducation struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Label       string
	School      string
	Description string
	StartDate   time.Time
	EndDate     sql.NullTime
	UserID      uuid.UUID
}

type RawExperience struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Title        string
	Organization string
	Description  string
	StartDate    time.Time
	EndDate      sql.NullTime
	UserID       uuid.UUID
}

type RawExperienceStack struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ExperienceID uuid.UUID
	StackID      uuid.UUID
}

type RawHobby struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Label     string
	UserID    uuid.UUID
}

type RawStack struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Label     string
	UserID    uuid.UUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
