// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Offer struct {
	ID                      int32
	CreatedAt               time.Time
	UpdatedAt               time.Time
	Label                   string
	Organization            string
	OrganizationDescription sql.NullString
	Missions                string
	Stack                   sql.NullString
	ExpectedProfile         string
	Miscellaneous           sql.NullString
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
