// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: offers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers(
    id,
    created_at,
    updated_at,
    label,
    organization,
    organization_description,
    missions,
    stack,
    expected_profile,
    miscellaneous,
    user_id
)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, label, organization, organization_description, missions, stack, expected_profile, miscellaneous, user_id
`

type CreateOfferParams struct {
	Label                   string
	Organization            string
	OrganizationDescription sql.NullString
	Missions                string
	Stack                   sql.NullString
	ExpectedProfile         string
	Miscellaneous           sql.NullString
	UserID                  uuid.UUID
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, createOffer,
		arg.Label,
		arg.Organization,
		arg.OrganizationDescription,
		arg.Missions,
		arg.Stack,
		arg.ExpectedProfile,
		arg.Miscellaneous,
		arg.UserID,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Organization,
		&i.OrganizationDescription,
		&i.Missions,
		&i.Stack,
		&i.ExpectedProfile,
		&i.Miscellaneous,
		&i.UserID,
	)
	return i, err
}
