// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_stacks.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRawStack = `-- name: CreateRawStack :one
INSERT INTO raw_stacks(id, created_at, updated_at, label, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, label, user_id
`

type CreateRawStackParams struct {
	Label  string
	UserID uuid.UUID
}

func (q *Queries) CreateRawStack(ctx context.Context, arg CreateRawStackParams) (RawStack, error) {
	row := q.db.QueryRowContext(ctx, createRawStack, arg.Label, arg.UserID)
	var i RawStack
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.UserID,
	)
	return i, err
}
