// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_project_stacks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRawprojectStack = `-- name: CreateRawprojectStack :one
WITH inserted_raw_project_stack as(
    INSERT INTO raw_project_stacks(id, created_at, updated_at, project_id, stack_id)
    VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2
    )
    RETURNING id, created_at, updated_at, project_id, stack_id
)
    SELECT 
        inserted_raw_project_stack.id, inserted_raw_project_stack.created_at, inserted_raw_project_stack.updated_at, inserted_raw_project_stack.project_id, inserted_raw_project_stack.stack_id,
        raw_projects.label AS project_label,
        raw_stacks.label AS stack_label
    FROM inserted_raw_project_stack
    INNER JOIN raw_projects ON raw_projects.id = inserted_raw_project_stack.project_id
    INNER JOIN raw_stacks ON raw_stacks.id = inserted_raw_project_stack.stack_id
`

type CreateRawprojectStackParams struct {
	ProjectID uuid.UUID
	StackID   uuid.UUID
}

type CreateRawprojectStackRow struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ProjectID    uuid.UUID
	StackID      uuid.UUID
	ProjectLabel string
	StackLabel   string
}

func (q *Queries) CreateRawprojectStack(ctx context.Context, arg CreateRawprojectStackParams) (CreateRawprojectStackRow, error) {
	row := q.db.QueryRowContext(ctx, createRawprojectStack, arg.ProjectID, arg.StackID)
	var i CreateRawprojectStackRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.StackID,
		&i.ProjectLabel,
		&i.StackLabel,
	)
	return i, err
}
