// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_hobbies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRawHobby = `-- name: CreateRawHobby :one
INSERT INTO raw_hobbies(id, created_at, updated_at, label, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, label, user_id
`

type CreateRawHobbyParams struct {
	Label  string
	UserID uuid.UUID
}

func (q *Queries) CreateRawHobby(ctx context.Context, arg CreateRawHobbyParams) (RawHobby, error) {
	row := q.db.QueryRowContext(ctx, createRawHobby, arg.Label, arg.UserID)
	var i RawHobby
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.UserID,
	)
	return i, err
}
