// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_projects.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRawProject = `-- name: CreateRawProject :one
INSERT INTO raw_projects(id, created_at, updated_at, label, description, start_date, end_date, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, label, description, start_date, end_date, user_id
`

type CreateRawProjectParams struct {
	Label       string
	Description string
	StartDate   time.Time
	EndDate     sql.NullTime
	UserID      uuid.UUID
}

func (q *Queries) CreateRawProject(ctx context.Context, arg CreateRawProjectParams) (RawProject, error) {
	row := q.db.QueryRowContext(ctx, createRawProject,
		arg.Label,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	var i RawProject
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
	)
	return i, err
}
