// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_hobbies.sql

package database

import (
	"context"
)

const createRawHobby = `-- name: CreateRawHobby :one
INSERT INTO raw_hobbies(id, created_at, updated_at, label)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1
)
RETURNING id, created_at, updated_at, label, user_id
`

func (q *Queries) CreateRawHobby(ctx context.Context, label string) (RawHobby, error) {
	row := q.db.QueryRowContext(ctx, createRawHobby, label)
	var i RawHobby
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.UserID,
	)
	return i, err
}
