// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: offers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers(
    id,
    created_at,
    updated_at,
    title,
    organization,
    organization_description,
    missions,
    stack,
    expected_profile,
    miscellaneous,
    user_id
)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at, title, organization, organization_description, missions, stack, expected_profile, miscellaneous, user_id
`

type CreateOfferParams struct {
	Title                   string
	Organization            string
	OrganizationDescription sql.NullString
	Missions                []string
	Stack                   []string
	ExpectedProfile         []string
	Miscellaneous           []string
	UserID                  uuid.UUID
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, createOffer,
		arg.Title,
		arg.Organization,
		arg.OrganizationDescription,
		pq.Array(arg.Missions),
		pq.Array(arg.Stack),
		pq.Array(arg.ExpectedProfile),
		pq.Array(arg.Miscellaneous),
		arg.UserID,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Organization,
		&i.OrganizationDescription,
		pq.Array(&i.Missions),
		pq.Array(&i.Stack),
		pq.Array(&i.ExpectedProfile),
		pq.Array(&i.Miscellaneous),
		&i.UserID,
	)
	return i, err
}
