// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_educations.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRawEducation = `-- name: CreateRawEducation :one
INSERT INTO raw_educations(id, created_at, updated_at, label, school, description, start_date, end_date, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, label, school, description, start_date, end_date, user_id
`

type CreateRawEducationParams struct {
	Label       string
	School      string
	Description string
	StartDate   time.Time
	EndDate     sql.NullTime
	UserID      uuid.UUID
}

func (q *Queries) CreateRawEducation(ctx context.Context, arg CreateRawEducationParams) (RawEducation, error) {
	row := q.db.QueryRowContext(ctx, createRawEducation,
		arg.Label,
		arg.School,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	var i RawEducation
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Label,
		&i.School,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
	)
	return i, err
}
