// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_experiences.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createRawExperience = `-- name: CreateRawExperience :one
INSERT INTO raw_experiences(id, created_at, updated_at, title, organization, description, start_date, end_date, user_id)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, title, organization, description, start_date, end_date, user_id
`

type CreateRawExperienceParams struct {
	Title        string
	Organization string
	Description  string
	StartDate    time.Time
	EndDate      sql.NullTime
	UserID       uuid.UUID
}

func (q *Queries) CreateRawExperience(ctx context.Context, arg CreateRawExperienceParams) (RawExperience, error) {
	row := q.db.QueryRowContext(ctx, createRawExperience,
		arg.Title,
		arg.Organization,
		arg.Description,
		arg.StartDate,
		arg.EndDate,
		arg.UserID,
	)
	var i RawExperience
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Organization,
		&i.Description,
		&i.StartDate,
		&i.EndDate,
		&i.UserID,
	)
	return i, err
}
