// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: raw_experience_stacks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRawExperienceStack = `-- name: CreateRawExperienceStack :one
WITH inserted_raw_experience_stack as(
    INSERT INTO raw_experience_stacks(id, created_at, updated_at, experience_id, stack_id)
    VALUES (
        gen_random_uuid(),
        NOW(),
        NOW(),
        $1,
        $2
    )
    RETURNING id, created_at, updated_at, experience_id, stack_id
)
    SELECT 
        inserted_raw_experience_stack.id, inserted_raw_experience_stack.created_at, inserted_raw_experience_stack.updated_at, inserted_raw_experience_stack.experience_id, inserted_raw_experience_stack.stack_id,
        raw_experiences.title AS experience_title,
        raw_stacks.label AS stack_label
    FROM inserted_raw_experience_stack
    INNER JOIN raw_experiences ON raw_experiences.id = inserted_raw_experience_stack.experience_id
    INNER JOIN raw_stacks ON raw_stacks.id = inserted_raw_experience_stack.stack_id
`

type CreateRawExperienceStackParams struct {
	ExperienceID uuid.UUID
	StackID      uuid.UUID
}

type CreateRawExperienceStackRow struct {
	ID              uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ExperienceID    uuid.UUID
	StackID         uuid.UUID
	ExperienceTitle string
	StackLabel      string
}

func (q *Queries) CreateRawExperienceStack(ctx context.Context, arg CreateRawExperienceStackParams) (CreateRawExperienceStackRow, error) {
	row := q.db.QueryRowContext(ctx, createRawExperienceStack, arg.ExperienceID, arg.StackID)
	var i CreateRawExperienceStackRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExperienceID,
		&i.StackID,
		&i.ExperienceTitle,
		&i.StackLabel,
	)
	return i, err
}
